
 # Project information
site_name: Nutriguide
site_author: Skywalkers
site_description: >-
  Documentação para do projeto Nutriguide realizado na disciplina de
  Requisitos de Software na Universidade de Brasília


# Repository
repo_url: https://github.com/mdsreq-fga-unb/2023.2-NutriGuide
repo_name: NutriGuide


# Configuration
docs_dir: docs
theme: 
  hide_toc: true 
  name: material
  language: pt-BR
  icon: 
   repo: fontawesome/brands/github
  font: 
    text: Roboto
  features:
  - navigation.instant
  - navigation.section
  - navigation.path
  - navigation.top
  - tabs

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
      primary: green
      accent: orange 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
      primary:  green
      accent:  orange


# Page tree
nav: 
  - Início: index.md
  - Facção Skywalkers: historia_faccao/historia_faccao.md
  - Apresentações: 
    - Unidade 01 - 28/09/2023: apresentacoes/Unidade01.md
    - Unidade 02 - 26/10/2023: apresentacoes/Unidade02.md
    - Unidade 03 - 23/11/2023: apresentacoes/Unidade03.md
  - Visão:
    - Visão geral do produto: visao_produto/visao_do_produto.md
    - Visão geral do projeto: visao_projeto/visao_do_projeto.md
    - Processo de desenvolvimento: processo_desenvolvimento/processo_de_desenvolvimento.md
  - Requisitos do Produto:
    - Backlog: requisitos-produto/backlog.md
    - MVP: requisitos-produto/MVP.md
    - Alinhamento Backlog: requisitos-produto/alinhamento_backlog.md
  - Atividades Unidade 3: 
    - USM: unidade_3/USM.md
    - PBB: unidade_3/PBB.md
    - BDD: unidade_3/BDD.md
    - DoR e DoD: unidade_3/DoR_DoD.md
  - Verificação e Validação Beach Tennis CoordiMate: requisitos-produto/verificacaoguardioes.md
  - Documentação das Sprints:
    - Missão 1: documentacao_sprints/missao1.md
    - Missão 2: documentacao_sprints/missao2.md
    - Missão 3: documentacao_sprints/missao3.md

# Extensions
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences



